let BillingService,ErrorFactory,Helper;_155‍.x([["default",()=>BillingController]]);_155‍.w("../services",[["default",["BillingService"],function(v){BillingService=v}]]);_155‍.w("../utils",[["ErrorFactory",["ErrorFactory"],function(v){ErrorFactory=v}],["Helper",["Helper"],function(v){Helper=v}]]);


const { addBilling } = BillingService;

const {successResponse} = Helper;

               class BillingController {
/**
   * @static
   * @param {Request} req - The request from the endpoint.
   * @param {Response} res - The response returned by the method.
   * @param {Next} next
   * @memberof BillingController
   */
  static async addBilling(req, res, next) {
     try {
        const { customerId, amount, type } = req.body;
        const result = await addBilling(customerId, amount, type);
        return successResponse(res, {
           message: 'Transaction added',
           data: result
         });
      } catch (err) {
      _155‍.g.console.log(err)
      res.status(500).json({ status: "error", message: "error occured!" })
   }
 }
}